# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import app.promocode_pb2 as promocode__pb2


class PromocodeServiceStub(object):
    """Определение сервиса PromocodeService"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePromocode = channel.unary_unary(
            "/promocode.PromocodeService/CreatePromocode",
            request_serializer=promocode__pb2.CreatePromocodeRequest.SerializeToString,
            response_deserializer=promocode__pb2.Promocode.FromString,
        )
        self.GetPromocode = channel.unary_unary(
            "/promocode.PromocodeService/GetPromocode",
            request_serializer=promocode__pb2.GetPromocodeRequest.SerializeToString,
            response_deserializer=promocode__pb2.Promocode.FromString,
        )
        self.ListPromocodes = channel.unary_unary(
            "/promocode.PromocodeService/ListPromocodes",
            request_serializer=promocode__pb2.ListPromocodesRequest.SerializeToString,
            response_deserializer=promocode__pb2.ListPromocodesResponse.FromString,
        )
        self.UpdatePromocode = channel.unary_unary(
            "/promocode.PromocodeService/UpdatePromocode",
            request_serializer=promocode__pb2.UpdatePromocodeRequest.SerializeToString,
            response_deserializer=promocode__pb2.Promocode.FromString,
        )
        self.DeletePromocode = channel.unary_unary(
            "/promocode.PromocodeService/DeletePromocode",
            request_serializer=promocode__pb2.DeletePromocodeRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class PromocodeServiceServicer(object):
    """Определение сервиса PromocodeService"""

    def CreatePromocode(self, request, context):
        """Создает новый промокод"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPromocode(self, request, context):
        """Получает промокод по ID"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPromocodes(self, request, context):
        """Получает список промокодов владельца с пагинацией"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdatePromocode(self, request, context):
        """Обновляет существующий промокод"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeletePromocode(self, request, context):
        """Удаляет промокод"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PromocodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreatePromocode": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePromocode,
            request_deserializer=promocode__pb2.CreatePromocodeRequest.FromString,
            response_serializer=promocode__pb2.Promocode.SerializeToString,
        ),
        "GetPromocode": grpc.unary_unary_rpc_method_handler(
            servicer.GetPromocode,
            request_deserializer=promocode__pb2.GetPromocodeRequest.FromString,
            response_serializer=promocode__pb2.Promocode.SerializeToString,
        ),
        "ListPromocodes": grpc.unary_unary_rpc_method_handler(
            servicer.ListPromocodes,
            request_deserializer=promocode__pb2.ListPromocodesRequest.FromString,
            response_serializer=promocode__pb2.ListPromocodesResponse.SerializeToString,
        ),
        "UpdatePromocode": grpc.unary_unary_rpc_method_handler(
            servicer.UpdatePromocode,
            request_deserializer=promocode__pb2.UpdatePromocodeRequest.FromString,
            response_serializer=promocode__pb2.Promocode.SerializeToString,
        ),
        "DeletePromocode": grpc.unary_unary_rpc_method_handler(
            servicer.DeletePromocode,
            request_deserializer=promocode__pb2.DeletePromocodeRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "promocode.PromocodeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class PromocodeService(object):
    """Определение сервиса PromocodeService"""

    @staticmethod
    def CreatePromocode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/promocode.PromocodeService/CreatePromocode",
            promocode__pb2.CreatePromocodeRequest.SerializeToString,
            promocode__pb2.Promocode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetPromocode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/promocode.PromocodeService/GetPromocode",
            promocode__pb2.GetPromocodeRequest.SerializeToString,
            promocode__pb2.Promocode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListPromocodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/promocode.PromocodeService/ListPromocodes",
            promocode__pb2.ListPromocodesRequest.SerializeToString,
            promocode__pb2.ListPromocodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdatePromocode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/promocode.PromocodeService/UpdatePromocode",
            promocode__pb2.UpdatePromocodeRequest.SerializeToString,
            promocode__pb2.Promocode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeletePromocode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/promocode.PromocodeService/DeletePromocode",
            promocode__pb2.DeletePromocodeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
